# Generated by Django 3.2.5 on 2021-07-29 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50, null=True)),
                ('gioitinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='', max_length=10, null=True)),
                ('ngaysinh', models.DateField(null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Baitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50, null=True)),
                ('mota', models.CharField(max_length=1000, null=True)),
                ('giaovienhd', models.CharField(max_length=50, null=True)),
                ('filebaocao', models.FileField(upload_to='')),
                ('filezip', models.FileField(upload_to='')),
                ('nguoidung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.nguoidung')),
            ],
        ),
    ]
